// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsxwbqjldefepebiuqdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zeHdicWpsZGVmZXBlYml1cWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTQ4MzIsImV4cCI6MjA2ODI3MDgzMn0.iBvmz4O3_N4nQB4I42vXHEVoRG_gMy0j2Fa8JElfjJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});